export const constans = {
  COIN: {
    SET_COIN_SUCCESS: 'SET_COIN_SUCCESS',
    SET_COIN_FAIL: 'SET_COIN_FAIL',

    SET_RANGE_SUCCESS: 'SET_RANGE_SUCCESS',
    SET_RANGE_FAIL: 'SET_RANGE_FAIL'
  }
}